<?php
// i18n-map.php @generated by automattic/jetpack-composer-plugin
return array(
  'domain' => 'jetpack-backup',
  'type' => 'plugins',
  'packages' => array(
    'jetpack-password-checker' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-password-checker',
      'ver' => '0.2.2',
    ),
    'jetpack-assets' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-assets',
      'ver' => '1.17.5',
    ),
    'jetpack-tracking' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-tracking',
      'ver' => '1.14.3',
    ),
    'jetpack-heartbeat' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-heartbeat',
      'ver' => '1.4.0',
    ),
    'jetpack-connection' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-connection',
      'ver' => '1.36.4',
    ),
    'jetpack-idc' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-identity-crisis',
      'ver' => '0.7.4',
    ),
    'jetpack-backup-pkg' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-backup',
      'ver' => '1.2.4',
    ),
    'jetpack-config' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-config',
      'ver' => '1.6.1',
    ),
    'jetpack-connection-ui' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-connection-ui',
      'ver' => '2.3.7',
    ),
    'jetpack-sync' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-sync',
      'ver' => '1.30.0',
    ),
    'jetpack-my-jetpack' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-my-jetpack',
      'ver' => '0.6.3',
    ),
    'jetpack-admin-ui' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-admin-ui',
      'ver' => '0.2.4',
    ),
  ),
);
