<?php
// i18n-map.php @generated by automattic/jetpack-composer-plugin
return array(
  'domain' => 'jetpack-backup',
  'type' => 'plugins',
  'packages' => array(
    'jetpack-password-checker' => '0.2.0',
    'jetpack-assets' => '1.16.1',
    'jetpack-tracking' => '1.14.0',
    'jetpack-heartbeat' => '1.4.0',
    'jetpack-idc' => '0.6.2',
    'jetpack-backup-pkg' => '1.2.1',
    'jetpack-config' => '1.6.0',
    'jetpack-connection-ui' => '2.3.1',
    'jetpack-connection' => '1.35.0',
    'jetpack-sync' => '1.28.1',
    'jetpack-my-jetpack' => '0.3.1',
  ),
);
