<?php
// i18n-map.php @generated by automattic/jetpack-composer-plugin
return array(
  'domain' => 'jetpack-backup',
  'type' => 'plugins',
  'packages' => array(
    'jetpack-password-checker' => '0.2.9999999-dev',
    'jetpack-assets' => '1.16.9999999-dev',
    'jetpack-tracking' => '1.14.9999999-dev',
    'jetpack-heartbeat' => '1.4.9999999-dev',
    'jetpack-connection' => '1.36.9999999-dev',
    'jetpack-idc' => '0.6.9999999-dev',
    'jetpack-sync' => '1.29.9999999-dev',
    'jetpack-backup-pkg' => '1.2.9999999-dev',
    'jetpack-config' => '1.6.9999999-dev',
    'jetpack-connection-ui' => '2.3.9999999-dev',
    'jetpack-my-jetpack' => '0.4.9999999-dev',
  ),
);
